[project]
name = "mysite"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "sarasaranuranura", email = "wada121400@gmail.com" }
]
dependencies = []
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
